name: Build and Deploy static content to Pages

on:
    # Runs on pushes targeting the default branch
    push:
        branches: ['main']

jobs:
    build:
        name: build ${{ matrix.node_version }} and ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                node_version: ['16']
                os: [ubuntu-latest]

        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js ${{ matrix.node_version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node_version }}

            - name: pnpm install, build
              run: |
                  npm install pnpm -g
                  pnpm install
                  pnpm run build
                  echo 'build success'

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  if: ${{ github.ref == 'refs/heads/main' }}
                  github_token: ${{ secrets.GITHUB_TOKEN}}
                  publish_dir: ./public
